web:
  restart: always
  image: anomi/web
  links:
   - api:api
  environment:
   - VIRTUAL_HOST=*/, */*
api:
  restart: always
  image: anomi/api
  links:
    - redis:redis
  environment:
    - VIRTUAL_HOST=*/api, */api/*
redis:
  restart: always
  image: redis
  volumes:
   - /mnt/redis:/data
  command: redis-server --appendonly yes
haproxy:
  restart: always
  image: evquirk/haproxy
  links:
    - api:api
    - web:web
  ports:
    - 80:80
